### ISSUE TITLE
Import module 'Geohash' requires capital letter

### ISSUE THREAD

**Issue by ryanbaumann** [murphy214/berrl#24] opened 2016-03-29 02:22 UTC
Problem: Import module error for 'import geohash' on python 2.7.11, after retrieving package from pypy

In pipgeojson.py and pipgeohash.py, the module 'Geohash' is imported with a lower case letter 'geohash'.  The module import is case sensitive.  

I fixed the local copy with the following alias in the above two files:
`import Geohash as geohash`

To do:
Determine if scope is just python 2.7.11, or inclusive of python 3.4+ as well
Update library imports in pipgeojson.py and pipgeohash.py

**Comment by murphy214** [comment] 2016-03-29 03:33
Hey man! Thanks for reporting the issue! The problem is the build of geohash berrl uses is this   https://github.com/hkwi/python-geohash this one and in this build it uses the lower case geohash. I think you may have a different geohash build entirely installed (possibly) what package is in your site packages for geohash.py? 

I feel like it could be possible that because you already had a geohash module in your site-packages that it didn't install my dependency.

**Comment by ryanbaumann** [comment] 2016-03-29 04:04
Good observation @murphy214 - yes, it looks like I had a copy module of Geohash (uppercase) already installed - the folder name in site-packages has a capital first letter.  Probably from a prior install of geopandas.

Thanks!

**Comment by murphy214** [comment] 2016-03-29 21:51
Awesome! closing now, thanks for bringing it to my attention anyway!

**Closed by murphy214** 2016-03-29 21:51 UTC
